import * as variables from "./script3.js";

// This function changes which image is displayed
// Inputs: none
// Output: none
function changePhoto(){
    if (window.imgCounter < 4){ //If the images index is valid
        variables.mainImg.src = variables.images[window.imgCounter];
        variables.mainImg.alt = variables.alts[window.imgCounter];
        window.imgCounter ++;
    }else{ //Resets the images index to the beginning
        window.imgCounter = 0;
        variables.mainImg.src = variables.images[window.imgCounter];
        variables.mainImg.alt = variables.alts[window.imgCounter];
        window.imgCounter ++;
    }
    
}


// This function adds a grayscale filter from the specific image 'mainImg'
// Inputs: none
// Output: none
function darkenImg(){
    variables.mainImg.style.filter = 'grayscale(60%)';
}


// This function removes a grayscale filter from the specific image 'mainImg'
// Inputs: none
// Output: none
function lightenImg(){
    variables.mainImg.style.filter = 'grayscale(0%)';
}

// This function changes the background color of the specific button 'colorButton'
// Inputs: none
// Output: none
function changeColor(){
    const red = getRandomInt(0,255); 
    const green = getRandomInt(0,255);
    const blue = getRandomInt(0,255);
    
    variables.colorButton.style.backgroundColor = `rgb(${red}, ${green}, ${blue})`; // changes the rgb values in the style of the button using the random numbers generated by the random number function
}


// This function creates a random whole number between the variables 'min' and 'max'
// Inputs: (min -> minimum number output, max -> maximum number output)
// Output: Int -> int between min and max
// Credit: This function was taken from a program I wrote in ATLS 2200
function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min) + min); // The maximum is exclusive and the minimum is inclusive
}

export {changePhoto, darkenImg, lightenImg, changeColor, getRandomInt};